// 동물퀴즈 데이터: 총 113개 (육지 63 / 바다 23 / 곤충 16 / 공룡 11)
// category: 'land' | 'sea' | 'insect' | 'dino'
// 힌트는 비슷한 동물과 헷갈리지 않도록, 그 동물만의 고유한 특징이 먼저 나오게 구성함
const ANIMALS = [
  // ===== 육지동물 - 포유류 (46) =====
  { name: "호랑이", emoji: "🐯", category: "land", aliases: ["범"], hints: ["나는 갈색 몸에 검은 줄무늬가 있어요", "나는 정글의 왕이라고 불려요", "나는 어흥 하고 크게 울어요"] },
  { name: "사자", emoji: "🦁", category: "land", aliases: [], hints: ["나는 목 주위에 멋진 갈기가 있어요", "나는 초원에서 무리 지어 살아요", "나는 동물의 왕이라고 불려요"] },
  { name: "코끼리", emoji: "🐘", category: "land", aliases: [], hints: ["나는 긴 코로 물을 뿜어요", "나는 몸이 아주 크고 회색이에요", "나는 큰 귀를 펄럭거려요"] },
  { name: "기린", emoji: "🦒", category: "land", aliases: [], hints: ["나는 목이 아주 길어요", "나는 몸에 노란 무늬가 있어요", "나는 높은 곳의 나뭇잎을 따먹어요"] },
  { name: "얼룩말", emoji: "🦓", category: "land", aliases: [], hints: ["나는 검은 줄무늬와 흰 줄무늬가 있어요", "나는 말처럼 생겼어요", "나는 초원에서 무리 지어 뛰어다녀요"] },
  { name: "판다", emoji: "🐼", category: "land", aliases: [], hints: ["나는 몸이 하얗고 까만 무늬가 있어요", "나는 대나무를 아주 좋아해요", "나는 중국에서 살아요"] },
  { name: "곰", emoji: "🐻", category: "land", aliases: ["불곰"], hints: ["나는 몸집이 크고 갈색 털이 있어요", "나는 겨울에는 굴 속에서 잠을 자요", "나는 꿀을 아주 좋아해요"] },
  { name: "북극곰", emoji: "🐻‍❄️", category: "land", aliases: [], hints: ["나는 온몸이 하얀 털로 덮여있어요", "나는 눈과 얼음 위에서 살아요", "나는 헤엄을 아주 잘 쳐요"] },
  { name: "여우", emoji: "🦊", category: "land", aliases: [], hints: ["나는 주황빛 털에 배는 하얗고 꼬리 끝도 하얘요", "나는 늑대보다 몸집이 작고 날씬해요", "나는 전래동화에서 꾀가 많은 동물로 자주 나와요"] },
  { name: "늑대", emoji: "🐺", category: "land", aliases: [], hints: ["나는 회색 털에 몸집이 크고 다리가 길어요", "나는 무리를 지어 사냥해요", "나는 보름달을 보고 아우우 하고 길게 울어요"] },
  { name: "토끼", emoji: "🐰", category: "land", aliases: [], hints: ["나는 귀가 아주 길어요", "나는 깡충깡충 뛰어다녀요", "나는 당근을 좋아해요"] },
  { name: "다람쥐", emoji: "🐿️", category: "land", aliases: [], hints: ["나는 꼬리가 복슬복슬해요", "나는 나무를 잘 타요", "나는 도토리를 모아둬요"] },
  { name: "고슴도치", emoji: "🦔", category: "land", aliases: [], hints: ["나는 몸에 뾰족한 가시가 잔뜩 나 있어요", "나는 놀라면 몸을 동그랗게 말아요", "나는 밤에 움직여요"] },
  { name: "두더지", emoji: "🐾", category: "land", aliases: [], hints: ["나는 땅속에 굴을 파고 살아요", "나는 눈이 아주 작아요", "나는 손이 삽처럼 생겼어요"] },
  { name: "사슴", emoji: "🦌", category: "land", aliases: [], hints: ["나는 머리에 나뭇가지처럼 갈라진 뿔이 있어요", "나는 몸이 날씬하고 다리가 길어요", "나는 숲속을 사뿐사뿐 뛰어다녀요"] },
  { name: "순록", emoji: "🦌", category: "land", aliases: [], hints: ["나는 뿔이 크고 나뭇가지처럼 생겼어요", "나는 눈 덮인 곳에서 살아요", "나는 산타할아버지 썰매를 끌어요"] },
  { name: "낙타", emoji: "🐫", category: "land", aliases: [], hints: ["나는 등에 커다란 혹이 있어요", "나는 사막에서 살아요", "나는 물 없이도 오래 견딜 수 있어요"] },
  { name: "캥거루", emoji: "🦘", category: "land", aliases: [], hints: ["나는 배에 아기 주머니가 있어요", "나는 큰 뒷다리로 껑충 뛰어요", "나는 호주에서 살아요"] },
  { name: "코알라", emoji: "🐨", category: "land", aliases: [], hints: ["나는 나무 위에서 하루 종일 잠을 자요", "나는 유칼립투스 잎만 먹어요", "나는 호주에서 살아요"] },
  { name: "원숭이", emoji: "🐵", category: "land", aliases: [], hints: ["나는 몸집이 작고 꼬리가 길어요", "나는 나무를 잘 타고 매달려요", "나는 바나나를 좋아해요"] },
  { name: "고릴라", emoji: "🦍", category: "land", aliases: [], hints: ["나는 몸집이 아주 크고 검은 털로 덮여있어요", "나는 두 주먹으로 가슴을 쿵쿵 두드려요", "나는 꼬리가 없어요"] },
  { name: "침팬지", emoji: "🐒", category: "land", aliases: [], hints: ["나는 검은 털을 가진 아주 똑똑한 동물이에요", "나는 나뭇가지로 도구를 만들어 흰개미를 잡아먹어요", "나는 사람과 가장 많이 닮은 동물이에요"] },
  { name: "오랑우탄", emoji: "🦧", category: "land", aliases: [], hints: ["나는 온몸이 붉은 털로 덮여있어요", "나는 팔이 아주 길어요", "나는 나무 위에서 대부분 살아요"] },
  { name: "하마", emoji: "🦛", category: "land", aliases: [], hints: ["나는 입을 아주 크게 벌려요", "나는 물속에서 대부분 지내요", "나는 몸이 뚱뚱하고 회색이에요"] },
  { name: "코뿔소", emoji: "🦏", category: "land", aliases: ["무소"], hints: ["나는 코 위에 커다란 뿔이 있어요", "나는 피부가 두껍고 딱딱해요", "나는 몸집이 아주 커요"] },
  { name: "소", emoji: "🐄", category: "land", aliases: ["젖소"], hints: ["나는 사람에게 우유를 줘요", "나는 음매 하고 울어요", "나는 목에 방울을 달고 있기도 해요"] },
  { name: "말", emoji: "🐴", category: "land", aliases: [], hints: ["나는 갈기가 멋있고 다리가 길어요", "나는 아주 빠르게 달려요", "나는 히힝 하고 울어요"] },
  { name: "당나귀", emoji: "🐴", category: "land", aliases: [], hints: ["나는 말보다 몸집이 작고 귀가 아주 커요", "나는 등에 짐을 지고 나르는 걸 도와줘요", "나는 히이호 하고 울어요"] },
  { name: "염소", emoji: "🐐", category: "land", aliases: [], hints: ["나는 턱에 긴 수염이 있어요", "나는 뾰족한 뿔이 있어요", "나는 매애 하고 울어요"] },
  { name: "양", emoji: "🐑", category: "land", aliases: [], hints: ["나는 몸이 하얀 털로 복슬복슬해요", "나는 내 털을 깎아서 옷을 만들어줘요", "나는 매에 하고 울어요"] },
  { name: "돼지", emoji: "🐷", category: "land", aliases: [], hints: ["나는 코가 동글동글해요", "나는 꿀꿀 하고 울어요", "나는 진흙 목욕을 좋아해요"] },
  { name: "개", emoji: "🐶", category: "land", aliases: ["강아지"], hints: ["나는 멍멍 하고 짖어요", "나는 사람과 가장 친한 친구예요", "나는 꼬리를 흔들며 반가워해요"] },
  { name: "고양이", emoji: "🐱", category: "land", aliases: ["야옹이"], hints: ["나는 야옹 하고 울어요", "나는 수염이 나 있어요", "나는 밤에도 눈이 잘 보여요"] },
  { name: "생쥐", emoji: "🐭", category: "land", aliases: ["쥐"], hints: ["나는 몸집이 아주 작아요", "나는 치즈를 좋아해요", "나는 찍찍 소리를 내요"] },
  { name: "스컹크", emoji: "🐾", category: "land", aliases: [], hints: ["나는 몸에 하얗고 검은 줄무늬가 있어요", "나는 놀라면 아주 지독한 냄새를 뿜어요", "나는 꼬리가 복슬복슬해요"] },
  { name: "너구리", emoji: "🦝", category: "land", aliases: [], hints: ["나는 눈 주위가 까매서 마스크를 쓴 것 같아요", "나는 꼬리에 줄무늬가 있어요", "나는 밤에 돌아다녀요"] },
  { name: "수달", emoji: "🦦", category: "land", aliases: [], hints: ["나는 몸이 길쭉하고 헤엄을 아주 잘 쳐요", "나는 강가에 굴을 파고 살아요", "나는 물고기를 잡아먹어요"] },
  { name: "비버", emoji: "🦫", category: "land", aliases: [], hints: ["나는 앞니가 아주 커요", "나는 나무를 갉아서 댐을 만들어요", "나는 넓적한 꼬리로 헤엄쳐요"] },
  { name: "박쥐", emoji: "🦇", category: "land", aliases: [], hints: ["나는 밤에 날아다녀요", "나는 거꾸로 매달려 잠을 자요", "나는 눈 대신 소리로 앞을 봐요"] },
  { name: "미어캣", emoji: "🐾", category: "land", aliases: [], hints: ["나는 두 발로 서서 망을 봐요", "나는 무리 지어 함께 살아요", "나는 몸이 가늘고 길어요"] },
  { name: "나무늘보", emoji: "🦥", category: "land", aliases: [], hints: ["나는 아주아주 느리게 움직여요", "나는 나무에 거꾸로 매달려 지내요", "나는 하루 종일 잠을 자요"] },
  { name: "아르마딜로", emoji: "🐾", category: "land", aliases: [], hints: ["나는 딱딱한 등껍질을 가지고 있어요", "나는 놀라면 몸을 동그랗게 말아요", "나는 땅을 잘 파요"] },
  { name: "물소", emoji: "🐃", category: "land", aliases: [], hints: ["나는 뿔이 머리 뒤로 넓게 휘어져 있어요", "나는 진흙탕에서 뒹구는 걸 좋아해요", "나는 논에서 농부 아저씨의 일을 도와줘요"] },
  { name: "들소", emoji: "🦬", category: "land", aliases: ["버팔로"], hints: ["나는 어깨에 커다란 혹이 봉긋 솟아있어요", "나는 온몸이 짙은 갈색 털로 덮여있고 머리가 커요", "나는 넓은 초원에서 무리 지어 살아요"] },
  { name: "치타", emoji: "🐾", category: "land", aliases: [], hints: ["나는 세상에서 가장 빠르게 달려요", "나는 몸에 검은 점무늬가 있어요", "나는 눈 밑에 눈물 자국 같은 줄이 있어요"] },
  { name: "천산갑", emoji: "🐾", category: "land", aliases: [], hints: ["나는 온몸이 딱딱한 비늘로 덮여있어요", "나는 위험하면 몸을 동그랗게 공처럼 말아요", "나는 긴 혀로 개미와 흰개미를 핥아먹어요"] },

  // ===== 육지동물 - 새/기타 (5) =====
  { name: "닭", emoji: "🐔", category: "land", aliases: [], hints: ["나는 머리에 빨간 볏이 있어요", "나는 꼬끼오 하고 울어서 아침을 알려요", "나는 매일 아침 알을 낳아요"] },
  { name: "오리", emoji: "🦆", category: "land", aliases: [], hints: ["나는 부리가 넓적하고 노란색이에요", "나는 발에 물갈퀴가 있어서 헤엄을 잘 쳐요", "나는 꽥꽥 하고 울어요"] },
  { name: "플라밍고", emoji: "🦩", category: "land", aliases: ["플라멩고"], hints: ["나는 온몸이 분홍색이에요", "나는 다리가 아주 길고 한쪽 다리로 서 있어요", "나는 목이 에스자처럼 구부러져 있어요"] },
  { name: "비둘기", emoji: "🕊️", category: "land", aliases: [], hints: ["나는 도시 어디에서나 볼 수 있는 새예요", "나는 구구 하고 울어요", "나는 사람이 떨어뜨린 과자 부스러기를 잘 주워먹어요"] },
  { name: "가재", emoji: "🦞", category: "land", aliases: [], hints: ["나는 작은 랍스터처럼 생긴 민물 동물이에요", "나는 커다란 집게발이 두 개 있어요", "나는 맑은 시냇물 돌 밑에 숨어 살아요"] },

  // ===== 육지동물 - 파충류/양서류 (12) =====
  { name: "악어", emoji: "🐊", category: "land", aliases: [], hints: ["나는 주둥이가 길고 뾰족해요", "나는 물속에 몸을 숨기고 먹이를 기다려요", "나는 눈물을 흘리는 척 연기를 잘한다고 해요"] },
  { name: "뱀", emoji: "🐍", category: "land", aliases: [], hints: ["나는 몸이 길쭉하고 다리가 없어요", "나는 혀를 날름거리며 냄새를 맡아요", "나는 허물을 벗으면서 자라요"] },
  { name: "도마뱀", emoji: "🦎", category: "land", aliases: [], hints: ["나는 꼬리가 잘려도 다시 자라요", "나는 몸이 비늘로 덮여있어요", "나는 벽도 잘 기어올라요"] },
  { name: "카멜레온", emoji: "🦎", category: "land", aliases: [], hints: ["나는 몸의 색깔을 바꿀 수 있어요", "나는 눈이 따로따로 움직여요", "나는 혀가 아주 길게 늘어나요"] },
  { name: "이구아나", emoji: "🦎", category: "land", aliases: [], hints: ["나는 등에 뾰족한 돌기가 줄지어 있어요", "나는 나무 위에서 햇볕을 쬐어요", "나는 초록색 몸을 가지고 있어요"] },
  { name: "거북이", emoji: "🐢", category: "land", aliases: [], hints: ["나는 등에 단단한 등껍질을 지고 다녀요", "나는 아주 느리게 걸어요", "나는 위험하면 등껍질 속으로 숨어요"] },
  { name: "개구리", emoji: "🐸", category: "land", aliases: [], hints: ["나는 개굴개굴 하고 울어요", "나는 폴짝폴짝 뛰어다녀요", "나는 올챙이에서 자라났어요"] },
  { name: "두꺼비", emoji: "🐸", category: "land", aliases: [], hints: ["나는 개구리와 닮았지만 피부가 우툴두툴해요", "나는 느릿느릿 걸어다녀요", "나는 밤에 움직여요"] },
  { name: "아나콘다", emoji: "🐍", category: "land", aliases: [], hints: ["나는 세상에서 가장 크고 무거운 뱀이에요", "나는 물속에서도 살 수 있어요", "나는 먹이를 몸으로 칭칭 감아요"] },
  { name: "코브라", emoji: "🐍", category: "land", aliases: [], hints: ["나는 화가 나면 목을 넓게 펴요", "나는 독을 가지고 있어요", "나는 피리 소리에 맞춰 춤추듯 움직여요"] },
  { name: "청개구리", emoji: "🐸", category: "land", aliases: [], hints: ["나는 몸이 초록색이고 몸집이 아주 작아요", "나는 나뭇잎이나 나뭇가지에 붙어살아요", "나는 발끝에 동그란 빨판이 있어서 유리에도 붙어요"] },
  { name: "앨리게이터", emoji: "🐊", category: "land", aliases: [], hints: ["나는 주둥이가 넓적하고 둥글어요", "나는 늪에서 살아요", "나는 이빨이 아주 많아요"] },

  // ===== 바다동물 (23) =====
  { name: "고래", emoji: "🐋", category: "sea", aliases: [], hints: ["나는 세상에서 가장 몸집이 큰 바다 동물이에요", "나는 등에 있는 구멍으로 물을 하늘 높이 뿜어요", "나는 노래하듯 소리를 내서 서로 이야기해요"] },
  { name: "범고래", emoji: "🐬", category: "sea", aliases: ["오르카"], hints: ["나는 몸이 까맣고 하얘요", "나는 바다의 사냥꾼이라고 불려요", "나는 무리를 지어 다녀요"] },
  { name: "돌고래", emoji: "🐬", category: "sea", aliases: [], hints: ["나는 몸이 매끈하고 회색이에요", "나는 높이 점프하는 걸 좋아해요", "나는 끼익끼익 소리를 내며 친구와 이야기해요"] },
  { name: "벨루가", emoji: "🐳", category: "sea", aliases: ["흰고래"], hints: ["나는 온몸이 새하얀 색이에요", "나는 이마가 동그랗게 볼록 튀어나와 있어요", "나는 차가운 북극 바다에서 살아요"] },
  { name: "상어", emoji: "🦈", category: "sea", aliases: [], hints: ["나는 이빨이 아주 날카롭고 많아요", "나는 등지느러미가 물 위로 삐죽 나와요", "나는 헤엄을 아주 잘 쳐요"] },
  { name: "귀상어", emoji: "🦈", category: "sea", aliases: [], hints: ["나는 머리가 망치처럼 옆으로 넓적하게 생겼어요", "나는 머리 양쪽 끝에 눈이 달려있어요", "나는 무리를 지어 헤엄치는 걸 좋아해요"] },
  { name: "문어", emoji: "🐙", category: "sea", aliases: [], hints: ["나는 다리가 8개이고 몸이 말랑말랑한 풍선 같아요", "나는 다리 빨판으로 물건에 딱 붙어요", "나는 위험하면 까만 먹물을 뿜어요"] },
  { name: "오징어", emoji: "🦑", category: "sea", aliases: [], hints: ["나는 몸이 화살처럼 길쭉하고 다리가 10개예요", "나는 물을 뿜어내며 아주 빠르게 헤엄쳐요", "나는 위험하면 까만 먹물을 뿜어요"] },
  { name: "해파리", emoji: "🎐", category: "sea", aliases: [], hints: ["나는 몸이 투명하고 말랑말랑해요", "나는 촉수에 닿으면 따끔해요", "나는 물속을 둥둥 떠다녀요"] },
  { name: "불가사리", emoji: "⭐", category: "sea", aliases: [], hints: ["나는 몸이 별 모양이에요", "나는 다리가 다시 자라날 수 있어요", "나는 바다 밑바닥에서 천천히 움직여요"] },
  { name: "게", emoji: "🦀", category: "sea", aliases: [], hints: ["나는 다리로 옆으로 걸어요", "나는 커다란 집게발이 있어요", "나는 딱딱한 껍데기를 가지고 있어요"] },
  { name: "새우", emoji: "🦐", category: "sea", aliases: [], hints: ["나는 몸이 투명하고 구부러져 있어요", "나는 수염이 길어요", "나는 톡톡 튀듯이 헤엄쳐요"] },
  { name: "조개", emoji: "🐚", category: "sea", aliases: [], hints: ["나는 딱딱한 두 개의 껍데기를 가지고 있어요", "나는 모래 속에 숨어 살아요", "나는 위험하면 껍데기를 꼭 닫아요"] },
  { name: "소라", emoji: "🐚", category: "sea", aliases: [], hints: ["나는 뾰족뾰족한 나선 모양 껍데기를 가졌어요", "나는 껍데기에 귀를 대면 파도 소리가 들려요", "나는 바다 밑을 천천히 기어다녀요"] },
  { name: "해마", emoji: "🐴", category: "sea", aliases: [], hints: ["나는 몸이 말의 머리처럼 생겼어요", "나는 꼬리로 해초를 감고 매달려요", "나는 아빠가 아기를 배주머니에서 키워요"] },
  { name: "복어", emoji: "🐡", category: "sea", aliases: [], hints: ["나는 놀라면 몸이 풍선처럼 부풀어요", "나는 몸에 뾰족한 가시가 있어요", "나는 독을 가지고 있어요"] },
  { name: "물개", emoji: "🦭", category: "sea", aliases: [], hints: ["나는 귀에 작은 지느러미 같은 것이 뾰족 나와 있어요", "나는 지느러미 발로 뒤뚱뒤뚱 걸어요", "나는 멍멍 짖는 듯한 소리를 내요"] },
  { name: "바다표범", emoji: "🦭", category: "sea", aliases: [], hints: ["나는 몸에 동글동글한 점무늬가 있어요", "나는 얼음 위에서 배로 미끄러지듯 움직여요", "나는 헤엄을 아주 잘 쳐요"] },
  { name: "바다코끼리", emoji: "🦭", category: "sea", aliases: [], hints: ["나는 긴 상아 두 개가 튀어나와 있어요", "나는 몸집이 아주 크고 뚱뚱해요", "나는 차가운 바다에서 살아요"] },
  { name: "펭귄", emoji: "🐧", category: "sea", aliases: [], hints: ["나는 날지는 못하지만 헤엄은 잘 쳐요", "나는 뒤뚱뒤뚱 걸어다녀요", "나는 검은색과 흰색 옷을 입은 것 같아요"] },
  { name: "흰동가리", emoji: "🐠", category: "sea", aliases: ["니모", "클라운피시"], hints: ["나는 몸이 주황색에 흰 줄무늬가 있어요", "나는 말미잘 속에 숨어 살아요", "나는 애니메이션 주인공으로 유명해요"] },
  { name: "장어", emoji: "🐍", category: "sea", aliases: [], hints: ["나는 몸이 길고 미끈미끈해요", "나는 뱀처럼 헤엄쳐요", "나는 좁은 바위 틈에 숨어요"] },
  { name: "산호", emoji: "🪸", category: "sea", aliases: [], hints: ["나는 알록달록한 색깔을 가지고 있어요", "나는 바닷속에서 나무처럼 자라요", "나는 작은 물고기들의 집이 되어줘요"] },

  // ===== 곤충 (16) =====
  { name: "나비", emoji: "🦋", category: "insect", aliases: [], hints: ["나는 알록달록한 날개가 두 쌍 있어요", "나는 꽃 사이를 훨훨 날아다녀요", "나는 애벌레였다가 번데기를 거쳐 변신해요"] },
  { name: "꿀벌", emoji: "🐝", category: "insect", aliases: ["벌"], hints: ["나는 윙윙 소리를 내며 날아다녀요", "나는 꽃에서 꿀을 모아요", "나는 침을 쏠 수 있어요"] },
  { name: "개미", emoji: "🐜", category: "insect", aliases: [], hints: ["나는 몸집은 작지만 힘이 아주 세요", "나는 줄지어 열심히 걸어다녀요", "나는 땅속에 집을 짓고 살아요"] },
  { name: "무당벌레", emoji: "🐞", category: "insect", aliases: [], hints: ["나는 등이 빨갛고 까만 점이 있어요", "나는 몸이 동그랗고 작아요", "나는 나뭇잎 위를 기어다녀요"] },
  { name: "잠자리", emoji: "🐾", category: "insect", aliases: [], hints: ["나는 날개가 얇고 투명해요", "나는 눈이 아주 크고 동그래요", "나는 공중에서 멈춰 떠 있을 수 있어요"] },
  { name: "매미", emoji: "🐾", category: "insect", aliases: [], hints: ["나는 여름에 맴맴 하고 크게 울어요", "나는 나무에 딱 붙어 있어요", "나는 땅속에서 오래오래 지내다 나와요"] },
  { name: "사슴벌레", emoji: "🪲", category: "insect", aliases: [], hints: ["나는 머리에 사슴뿔처럼 생긴 큰 턱이 있어요", "나는 나무 수액을 먹어요", "나는 힘이 아주 세요"] },
  { name: "장수풍뎅이", emoji: "🪲", category: "insect", aliases: [], hints: ["나는 머리에 코뿔소 같은 뿔이 한 개 있어요", "나는 몸이 반짝반짝 윤이 나요", "나는 힘이 세서 무거운 것도 밀어요"] },
  { name: "메뚜기", emoji: "🦗", category: "insect", aliases: [], hints: ["나는 뒷다리가 길고 튼튼해요", "나는 폴짝폴짝 멀리 뛰어요", "나는 풀밭에서 살아요"] },
  { name: "귀뚜라미", emoji: "🦗", category: "insect", aliases: [], hints: ["나는 가을 밤에 귀뚤귀뚤 울어요", "나는 뒷다리를 비벼서 소리를 내요", "나는 어두운 곳을 좋아해요"] },
  { name: "파리", emoji: "🪰", category: "insect", aliases: [], hints: ["나는 윙윙거리며 여기저기 날아다녀요", "나는 손과 발을 비벼요", "나는 음식 냄새를 잘 맡아요"] },
  { name: "모기", emoji: "🦟", category: "insect", aliases: [], hints: ["나는 앵앵 소리를 내며 날아다녀요", "나는 사람의 피를 빨아먹어요", "나는 물리면 아주 간지러워요"] },
  { name: "거미", emoji: "🕷️", category: "insect", aliases: [], hints: ["나는 다리가 여덟 개예요", "나는 거미줄을 쳐서 먹이를 잡아요", "나는 곤충을 잡아먹어요"] },
  { name: "반딧불이", emoji: "🐾", category: "insect", aliases: [], hints: ["나는 배 끝에서 반짝반짝 빛이 나요", "나는 여름밤에 날아다녀요", "나는 깨끗한 곳에서만 살아요"] },
  { name: "사마귀", emoji: "🐾", category: "insect", aliases: [], hints: ["나는 앞다리가 낫처럼 뾰족해요", "나는 다른 곤충을 잡아먹어요", "나는 가만히 기다렸다가 순식간에 잡아채요"] },
  { name: "콩벌레", emoji: "🐛", category: "insect", aliases: ["쥐며느리"], hints: ["나는 건드리면 몸을 동그란 공처럼 돌돌 말아요", "나는 다리가 아주 많아요", "나는 축축하고 그늘진 돌 밑에 숨어 살아요"] },

  // ===== 공룡 (11) =====
  { name: "티라노사우루스", emoji: "🦖", category: "dino", aliases: ["티렉스"], hints: ["나는 이빨이 아주 크고 날카로워요", "나는 몸집이 크지만 앞다리는 아주 짧아요", "나는 공룡 중에 가장 무서운 사냥꾼이었어요"] },
  { name: "트리케라톱스", emoji: "🦕", category: "dino", aliases: [], hints: ["나는 얼굴에 커다란 뿔이 세 개 있어요", "나는 머리에 방패 같은 뼈가 있어요", "나는 풀을 먹는 초식 공룡이었어요"] },
  { name: "스테고사우루스", emoji: "🦕", category: "dino", aliases: [], hints: ["나는 등에 커다란 뼈판이 줄지어 있어요", "나는 꼬리에 뾰족한 가시가 있어요", "나는 몸집에 비해 머리가 아주 작아요"] },
  { name: "브라키오사우루스", emoji: "🦕", category: "dino", aliases: [], hints: ["나는 목이 아주아주 길어요", "나는 키가 나무보다 커요", "나는 초식 공룡 중에서도 몸집이 아주 커요"] },
  { name: "벨로키랍토르", emoji: "🦖", category: "dino", aliases: [], hints: ["나는 몸집은 작지만 아주 빠르고 영리해요", "나는 발톱이 낫처럼 날카로워요", "나는 무리를 지어 사냥했어요"] },
  { name: "프테라노돈", emoji: "🦕", category: "dino", aliases: [], hints: ["나는 머리 뒤로 길게 뻗은 볏이 있어요", "나는 하늘을 나는 익룡이에요", "나는 부리에 이빨이 없어요"] },
  { name: "안킬로사우루스", emoji: "🦕", category: "dino", aliases: [], hints: ["나는 온몸이 딱딱한 갑옷 같은 뼈로 덮여있어요", "나는 꼬리 끝이 커다란 망치처럼 생겼어요", "나는 초식 공룡이었어요"] },
  { name: "파라사우롤로푸스", emoji: "🦕", category: "dino", aliases: [], hints: ["나는 머리에 길게 휘어진 볏이 있어요", "나는 볏으로 나팔 같은 소리를 냈어요", "나는 두 발로도 네 발로도 걸을 수 있었어요"] },
  { name: "스피노사우루스", emoji: "🦖", category: "dino", aliases: [], hints: ["나는 등에 커다란 돛처럼 생긴 뼈가 있어요", "나는 악어처럼 긴 주둥이를 가졌어요", "나는 물속에서도 헤엄쳤어요"] },
  { name: "케찰코아틀루스", emoji: "🦕", category: "dino", aliases: [], hints: ["나는 하늘을 나는 익룡 중에 가장 컸어요", "나는 날개를 펴면 비행기 날개만큼 컸어요", "나는 목이 길고 부리가 뾰족해요"] },
  { name: "파키케팔로사우루스", emoji: "🦕", category: "dino", aliases: [], hints: ["나는 머리뼈가 아주 두껍고 동그래요", "나는 머리로 서로 박치기를 했어요", "나는 두 발로 걸어다녔어요"] },
];
